%dev.webpserver.images-dir=./images

webpserver.images-dir=/images
webpserver.require-api-key-for-upload=false
webpserver.max-size-mb=16
webpserver.max-uploads-per-minute=20
webpserver.max-uploads-per-hour=100
webpserver.max-uploads-per-day=1000
webpserver.webp-quality=75.0
webpserver.webp-lossless=false

quarkus.http.root-path=/
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.swagger-ui.always-include=true
quarkus.jackson.property-naming-strategy=SNAKE_CASE
