
# WebP Server Configuration
%dev.webpserver.images-dir=./images
webpserver.images-dir=/images
webpserver.require-api-key-for-upload=false
webpserver.max-size-mb=16
webpserver.max-uploads-per-minute=20
webpserver.max-uploads-per-hour=100
webpserver.max-uploads-per-day=1000
webpserver.webp-quality=60
webpserver.webp-lossless=false
webpserver.valid-sizes=100,200,400,800,1200,1900,2500

# HTTP Server Configuration
quarkus.http.root-path=/
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=*

# Swagger/OpenAPI Configuration
quarkus.smallrye-openapi.path=/q/openapi
%prod.quarkus.smallrye-openapi.enabled=false
quarkus.swagger-ui.path=/q/swagger-ui

# Miscellaneous
quarkus.jackson.property-naming-strategy=SNAKE_CASE
quarkus.banner.path=banner.txt
quarkus.log.console.format=%-5p %s%e%n

